# Support PRAVIEL development
# Your support helps preserve 5,000 years of human linguistic heritage

github: antonsoo
patreon: PRAVIEL
open_collective: praviel
ko_fi: PRAVIEL
liberapay: antonsoloviev
custom:
  - https://buy.stripe.com/6oU8wOfCe7ccbhefx0ew800
  - https://www.paypal.com/ncp/payment/PY77DTBNL5D88
