# Support PRAVIEL development
# Your support helps preserve 5,000 years of human linguistic heritage

github: antonsoo
patreon: AntonSoloviev
open_collective: antonsoloviev
ko_fi: antonsoloviev
liberapay: antonsoloviev
custom:
  - https://buy.stripe.com/6oU8wOfCe7ccbhefx0ew800
  - https://paypal.me/AntonS0
  - https://paypal.me/ancientlanguagesapp
