export type LanguageRoadmapPhase = {
  id: string;
  title: string;
  timeframe: string;
  summary: string;
  languages: string[];
  accent: string;
  note?: string;
};

export const languageRoadmapPhases: LanguageRoadmapPhase[] = [
  {
    id: "phase-1",
    title: "Phase 1 · Core Languages",
    timeframe: "Now Available",
    summary:
      "Comprehensive learning platform for foundational ancient languages. Each language includes: interactive reader with morphology, grammar lessons, vocabulary drills with spaced repetition, AI tutors trained on primary sources, cultural and historical context, and curated canonical texts. Not just a reader—a complete learning system.",
    accent: "from-[#E8C55B]/40 to-[#3b82f6]/30",
    languages: [
      "Classical Sanskrit",
      "Classical Chinese",
      "Pali",
      "Old Church Slavonic",
      "Ancient Aramaic",
      "Classical Arabic",
      "Old Norse",
      "Middle Egyptian",
      "Old English",
      "Yehudit (Paleo-Hebrew)",
      "Coptic",
      "Ancient Sumerian",
      "Classical Tamil",
      "Classical Syriac",
      "Akkadian",
      "Vedic Sanskrit",
    ],
  },
  {
    id: "phase-2",
    title: "Phase 2 · Expanding Coverage",
    timeframe: "Coming Q1 2026",
    summary:
      "Additional ancient languages with the same comprehensive feature set, plus enhanced learning methods: video lessons from historical sites and manuscripts, photo-based exercises with real inscriptions, and advanced AI tutors. Continuing to build complete learning experiences, not simple text readers.",
    accent: "from-[#3b82f6]/30 to-[#a855f7]/25",
    languages: [
      "Classical Armenian",
      "Hittite",
      "Old Egyptian (Old Kingdom)",
      "Avestan",
      "Classical Nahuatl",
      "Classical Tibetan",
      "Old Japanese",
      "Classical Quechua",
      "Middle Persian (Pahlavi)",
      "Old Irish",
      "Gothic",
      "Geʽez",
      "Sogdian",
      "Ugaritic",
      "Tocharian A (Ārśi)",
      "Tocharian B (Kuśiññe)",
    ],
  },
  {
    id: "phase-3",
    title: "Phase 3 · Final Languages + Mobile",
    timeframe: "Coming H2 2026",
    summary:
      "Completing our coverage of major ancient writing systems with the same comprehensive learning platform. Plus: native iOS and Android apps with full offline support, community features for sharing annotations, and collaborative tools for classrooms and research groups.",
    accent: "from-[#a855f7]/25 to-[#f472b6]/25",
    note: "These languages will launch alongside mobile apps with embedded lexicons and full offline mode.",
    languages: [
      "Old Turkic (Orkhon)",
      "Etruscan",
      "Proto-Norse (Elder Futhark)",
      "Runic Old Norse (Younger Futhark)",
      "Old Persian (Ariya)",
      "Elamite",
      "Classic Maya (Chʼoltiʼ)",
      "Phoenician (Canaanite)",
      "Moabite",
      "Punic (Carthaginian)",
    ],
  },
];

export const languageEmoji: Record<string, string> = {
  "Classical Latin": "🏛️",
  "Koine Greek": "📖",
  "Classical Greek": "🏺",
  "Biblical Hebrew": "🕎",
  "Classical Sanskrit": "🪷",
  "Classical Chinese": "🐉",
  Pali: "☸️",
  "Old Church Slavonic": "☦️",
  "Ancient Aramaic": "🗣️",
  "Classical Arabic": "🌙",
  "Old Norse": "🪓",
  "Old Norse (Norrœnt mál)": "🪓",
  "Middle Egyptian": "👁️",
  "Old English": "🪢",
  "Yehudit (Paleo-Hebrew)": "🍎",
  "Coptic (Sahidic)": "⚖️",
  "Ancient Sumerian": "🔆",
  "Classical Tamil": "🪔",
  "Classical Syriac": "✝️",
  Akkadian: "🏹",
  "Vedic Sanskrit": "🕉️",
  "Classical Armenian": "🦅",
  Hittite: "🐂️",
  "Old Egyptian (Old Kingdom)": "🪲",
  Avestan: "🔥",
  "Classical Nahuatl": "🐆",
  "Classical Tibetan": "🏔️",
  "Old Japanese": "🗻",
  "Classical Quechua": "🦙",
  "Middle Persian (Pahlavi)": "🪙",
  "Old Irish": "☘️",
  Gothic: "⚔️",
  "Geʽez": "🦁",
  Sogdian: "🌌",
  Ugaritic: "🌄",
  "Tocharian A (Ārśi)": "🐫",
  "Tocharian B (Kuśiññe)": "🛕",
  "Old Turkic (Orkhon)": "🐺",
  Etruscan: "⚱️",
  "Proto-Norse (Elder Futhark)": "🏞",
  "Runic Old Norse (Younger Futhark)": "⛈️",
  "Old Persian (Ariya)": "👑",
  Elamite: "🐍",
  "Classic Maya (Chʼoltiʼ)": "🌽",
  "Phoenician (Canaanite)": "⛵",
  Moabite: "🐏",
  "Punic (Carthaginian)": "⚓",
};
