/**
 * Language data structure with proper TypeScript typing
 * Sourced from docs/archive/imported-docs-from-main-repo/TOP_TEN_WORKS_PER_LANGUAGE.md
 */

export interface Language {
  name: string;
  nativeName: string;
  sample: string;
  translation: string;
  script: string;
  color: string;
  emoji: string;
  description: string;
  topTenWorks: string[];
  writingInfo: string;
  fontClass?: string; // CSS class for font-family
  isRTL?: boolean; // Right-to-left script
  tier: "top" | "core";
}

export const languages: Language[] = [
  {
    name: "Classical Latin",
    nativeName: "LINGVA LATINA",
    sample: "ARMA·VIRVMQVE·CANO·TROIAE·QVI·PRIMVS·AB·ORIS",
    translation: "I sing of arms and the man, who first from the shores of Troy",
    script: "Roman capitals (A-Z without J/U/W)",
    color: "from-red-500 to-rose-600",
    emoji: "🏛️",
    description: "Most requested, foundational for Western education.",
    topTenWorks: [
      "Aeneid by Virgil",
      "Metamorphoses by Ovid",
      "De Rerum Natura by Lucretius",
      "Commentaries on the Gallic War by Julius Caesar",
      "Annals by Tacitus",
      "Ab Urbe Condita by Livy",
      "Odes by Horace",
      "Naturalis Historia by Pliny the Elder",
      "Satires by Juvenal",
      "Vulgate (Latin Bible) by Jerome",
    ],
    writingInfo:
      "Present text in Roman capitals with the classical inventory A B C D E F G H I K L M N O P Q R S T V X Y Z. Normalize input J→I, U→V, W→VV; map Æ/Œ→AE/OE. Use Y and Z primarily for Greek loans; Q occurs only as QV; retain K only where epigraphically fixed. Default to scriptio continua; optionally expose an \"Epigraphic divider\" toggle that inserts an interpunct (· U+00B7) as a word divider. Do not use macrons/breves; if vowel length must be surfaced, offer an \"apex mode\" using a combining acute. Numerals are Roman only with additive (IIII) or subtractive (IV) styles; prevent ligatures and any re-introduction of J/U/W or modern punctuation.",
    fontClass: "font-display",
    isRTL: false,
    tier: "top",
  },
  {
    name: "Koine Greek",
    nativeName: "ΚΟΙΝΗ ΔΙΑΛΕΚΤΟΣ",
    sample: "ΕΝΑΡΧΗΗΝΟΛΟΓΟΣΚΑΙΟΛΟΓΟΣΗΝΠΡΟΣΤΟΝΘΕΟΝ",
    translation: "In the beginning was the Word, and the Word was with God",
    script: "Greek capitals (scriptio continua, no accents)",
    color: "from-sky-500 to-indigo-500",
    emoji: "📖",
    description: "New Testament, Septuagint, Hellenistic philosophy.",
    topTenWorks: [
      "Septuagint (LXX)",
      "New Testament",
      "Jewish War by Flavius Josephus",
      "Parallel Lives by Plutarch",
      "Discourses & Enchiridion by Epictetus (via Arrian)",
      "Geographica by Strabo",
      "Almagest by Ptolemy",
      "On the Sublime (Pseudo-Longinus)",
      "Ecclesiastical History by Eusebius",
      "Anabasis of Alexander by Arrian",
    ],
    writingInfo:
      "Use the 24 Koine capitals (Α–Ω) with sigma as Σ only. Scriptio continua by default; allow inscriptional interpuncts when attested. Strip accents, breathings, and iota-subscripts; permit diaeresis only for genuine hiatus. Optional manuscript mode may overline nomina sacra. Numbers default to words, with optional Milesian numerals using stigma/koppa/sampi.",
    fontClass: "font-greek",
    isRTL: false,
    tier: "top",
  },
  {
    name: "Classical Greek",
    nativeName: "ΕΛΛΗΝΙΚΗ ΓΛΩΤΤΑ",
    sample: "ΜΗΝΙΝΑΕΙΔΕΘΕΑΠΗΛΗΙΑΔΕΩΑΧΙΛΗΟΣ",
    translation: "Sing, goddess, the wrath of Achilles, son of Peleus",
    script: "Greek capitals (Ionian/Eucleidean)",
    color: "from-blue-500 to-indigo-600",
    emoji: "🏺",
    description: "Homer, Plato, full Iliad with Perseus morphology.",
    topTenWorks: [
      "Iliad by Homer",
      "Odyssey by Homer",
      "Theogony by Hesiod",
      "Works and Days by Hesiod",
      "Oedipus Rex by Sophocles",
      "Antigone by Sophocles",
      "Medea by Euripides",
      "Histories by Herodotus",
      "History of the Peloponnesian War by Thucydides",
      "Republic by Plato",
    ],
    writingInfo:
      "Encode the 24 Ionian/Eucleidean capitals (Α–Ω) with sigma strictly as Σ—never lunate. Default to scriptio continua with optional interpuncts only when witnesses show them. Omit accents, breathings, and iota-subscripts; rely on fonts for uncial forms. Numerals follow Milesian or Attic systems as attested; no Arabic digits.",
    fontClass: "font-greek",
    isRTL: false,
    tier: "top",
  },
  {
    name: "Biblical Hebrew",
    nativeName: "יהודית",
    sample: "בראשית ברא אלהים את השמים ואת הארץ",
    translation: "In the beginning God created the heavens and the earth",
    script: "Unpointed square Hebrew",
    color: "from-amber-500 to-yellow-600",
    emoji: "🕎",
    description: "Torah, Prophets, Writings, theological studies.",
    topTenWorks: [
      "Genesis (Bereshit)",
      "Exodus (Shemot)",
      "Isaiah (Yeshayahu)",
      "Psalms (Tehillim)",
      "Deuteronomy (Devarim)",
      "Samuel (Shmuel)",
      "Kings (Melakhim)",
      "Jeremiah (Yirmeyahu)",
      "Ezekiel (Yehezkel)",
      "Job (Iyov)",
    ],
    writingInfo:
      "Use unpointed square Hebrew (Ketav Ashuri) right-to-left. Remove niqqud, te'amim, maqaf, sof pasuq, and modern punctuation unless the witness includes them. Separate words with simple spacing, keep matres lectionis as written, and spell numerals per the source.",
    fontClass: "font-hebrew",
    isRTL: true,
    tier: "top",
  },
  {
    name: "Classical Sanskrit",
    nativeName: "संस्कृतम्",
    sample: "धर्मक्षेत्रेकुरुक्षेत्रेसमवेतायुयुत्सवः",
    translation: "Gathered to fight on the field of dharma, the field of the Kurus",
    script: "Devanagari with full ligatures",
    color: "from-orange-500 to-red-600",
    emoji: "🪷",
    description: "Mahābhārata, Bhagavad-Gītā, Upaniṣads.",
    topTenWorks: [
      "Mahābhārata (incl. Bhagavad-Gītā)",
      "Rāmāyaṇa",
      "Bhagavad-Gītā",
      "Arthaśāstra (Kauṭilya)",
      "Aṣṭādhyāyī (Pāṇini)",
      "Abhijñānaśākuntalam (Kālidāsa)",
      "Meghadūta (Kālidāsa)",
      "Suśruta-saṁhitā",
      "Pañcatantra",
      "Yoga Sūtras of Patañjali",
    ],
    writingInfo:
      "Use Devanagari (or early Nāgarī) with full conjunct ligatures and scriptio continua. End sections only with danda or double danda (U+0964/U+0965); no Western punctuation. Remove editorial hyphens, allow avagraha (ऽ) only when attested, and spell numerals per the witness.",
    fontClass: "font-devanagari",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Classical Chinese",
    nativeName: "文言文",
    sample: "子曰學而時習之不亦說乎",
    translation: "The Master said: To learn and practice at the proper time—is that not a joy?",
    script: "Traditional Han characters, vertical columns right-to-left",
    color: "from-amber-400 to-emerald-500",
    emoji: "🐉",
    description: "Analects, Dao De Jing, classical poetry and statecraft texts.",
    topTenWorks: [
      "Analects of Confucius",
      "Dao De Jing (Laozi)",
      "The Art of War (Sun Tzu)",
      "Zhuangzi",
      "Records of the Grand Historian (Sima Qian)",
      "Mencius",
      "I Ching (Book of Changes)",
      "Classic of Poetry (Shijing)",
      "Book of Documents (Shujing)",
      "Zuo Zhuan",
    ],
    writingInfo:
      "Use traditional Hanzi without punctuation or spaces; default layout is vertical columns running top-to-bottom and ordered right-to-left. Do not normalize variant graphs or convert to simplified; numerals remain in Chinese characters (一二三…) and editorial marks like 、，。 appear only if attested in the witness.",
    fontClass: "font-cjk",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Old Church Slavonic",
    nativeName: "СЛОВѢНЬСКЪ ѨЗЫКЪ",
    sample: "СЛОВѢНЬСКЪѨЗЫКЪ",
    translation: "The Slavonic tongue",
    script: "Early Church Slavonic ustav",
    color: "from-purple-500 to-fuchsia-600",
    emoji: "☦️",
    description: "Cyrillic liturgical language, foundation of Slavic culture.",
    topTenWorks: [
      "Codex Zographensis (Gospels)",
      "Ostromir Gospel",
      "Sinai Psalter",
      "Proglas (Prologue to the Gospels)",
      "Lives of Cyril and Methodius",
      "Euchologium Sinaiticum",
      "Didactic Gospel (Constantine of Preslav)",
      "Svyatoslav's Miscellany",
      "Codex Marianus (Gospels)",
      "Kievan Glagolitic Sheets",
    ],
    writingInfo:
      "Prefer Glagolitic uncial for earliest witnesses; if Cyrillic, use early ustav with full yats/yers/izhitsa/fita inventory. No lowercase; keep titlo for nomina sacra and numeral letters. Use only ancient middle/high dots and paragraph marks for punctuation. Numbers are letters with titlo; never Arabic digits; retain yers (Ъ/Ь) and nasal vowels (Ѧ/Ѫ) exactly as written.",
    fontClass: "font-cyrillic",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Old Norse (Norrœnt mál)",
    nativeName: "ᚢᛚᚠᛁᛏ",
    sample: "GANGASKALSKYLIGUMNASON",
    translation: "A son of men must venture forth",
    script: "Medieval Latin script with þ/ð/æ",
    color: "from-emerald-500 to-lime-600",
    emoji: "🪓",
    description: "Viking Age sagas, Poetic Edda.",
    topTenWorks: [
      "Poetic Edda",
      "Prose Edda (Snorri Sturluson)",
      "Völsunga saga",
      "Egil's Saga",
      "Hávamál",
      "Njál's saga",
      "Laxdæla saga",
      "Heimskringla",
      "Grettir's Saga",
      "Eiríks saga rauða",
    ],
    writingInfo:
      "Use 12th–13th c. Icelandic/Norwegian Latin-script conventions: a b c d e f g h i k l m n o p q r s t u/v x y z plus þ, ð, æ, ǫ per witness. No lowercase distinction; avoid modern punctuation—only punctus, punctus elevatus/interrogativus where attested. Use tironian et (⁊) for “ok” when sources do, keep spellings unnormalized, and render numbers as Roman or spelled per the manuscript (never Arabic digits).",
    fontClass: "font-serif",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Middle Egyptian",
    nativeName: "𓂋𓈖𓎡𓅓𓏏",
    sample: "𓇋𓈖𓂓𓅱𓈙𓅱𓏏𓈖𓇋",
    translation: "I was Sinuhe",
    script: "Egyptian hieroglyphs",
    color: "from-yellow-600 to-amber-700",
    emoji: "👁️",
    description: "Tale of Sinuhe, Book of the Dead (2000-1300 BCE).",
    topTenWorks: [
      "Story of Sinuhe",
      "Coffin Texts",
      "Tale of the Shipwrecked Sailor",
      "Instruction of King Merikare",
      "Instruction of Amenemope",
      "Book of the Dead",
      "Prophecy of Neferti",
      "Report of Wenamun",
      "Merneptah Stele (Israel Stele)",
      "Shabaka Stone (Memphite Theology)",
    ],
    writingInfo:
      "Use Middle Egyptian hieroglyphs with canonical grouping, lines running right-to-left (or vertical) with signs facing right. No vowels, spaces, or modern punctuation; preserve determinatives/logograms exactly and omit editorial brackets. Use hieratic only when the witness demands it, and render numerals in hieroglyphic tallies.",
    fontClass: "font-serif", // Fallback – dedicated hieroglyph font handled where available
    isRTL: false,
    tier: "core",
  },
  {
    name: "Pali",
    nativeName: "𑀧𑀸𑀮𑀺",
    sample: "𑀤𑀫𑁆𑀧𑀸𑀤𑀸",
    translation: "Dhammapada (rendered in Brahmi)",
    script: "Asokan Brahmi (Sinhala toggle for palm-leaf witnesses)",
    color: "from-amber-500 to-orange-600",
    emoji: "☸️",
    description: "Theravada canon preserved in Sri Lanka and Southeast Asia; earliest stratum of the Buddha’s teachings.",
    topTenWorks: [
      "Dīgha Nikāya",
      "Majjhima Nikāya",
      "Dhammapada",
      "Jātaka Tales",
      "Visuddhimagga (Buddhaghosa)",
      "Saṃyutta Nikāya",
      "Aṅguttara Nikāya",
      "Milinda Pañha",
      "Vinaya Piṭaka",
      "Mahāvaṃsa",
    ],
    writingInfo:
      "Default to Asokan Brahmi with a selectable Sinhala hand; forbid Western punctuation—only danda and double-danda. Avoid later Devanāgarī, preserve matres lectionis, sandhi, and ligatures exactly as witnessed.",
    fontClass: "font-brahmi",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Ancient Aramaic",
    nativeName: "𐡀𐡓𐡌𐡉𐡕",
    sample: "𐡁𐡓𐡀 𐡀𐡋𐡄𐡉𐡌",
    translation: "“Created by Elohim” (Genesis in Imperial Aramaic)",
    script: "Imperial Aramaic consonantal alphabet",
    color: "from-rose-500 to-red-500",
    emoji: "🗣️",
    description: "Lingua franca of the Near East—imperial decrees, Dead Sea Scrolls, Elephantine papyri, and targumim.",
    topTenWorks: [
      "Wisdom of Ahiqar",
      "Targum Onkelos",
      "Genesis Apocryphon (1Q20)",
      "Book of Daniel (Aramaic chapters)",
      "Book of Ezra (Aramaic sections)",
      "Elephantine Papyri",
      "Zakkur Stele",
      "Tel Dan Stele",
      "Peshitta",
      "Aramaic Incantation Bowls",
    ],
    writingInfo:
      "Use Imperial Aramaic, right-to-left, with no vowel pointing or Western punctuation. Word dividers only where inscriptions show dots, otherwise scriptio continua; numerals spelled or rendered with stroke tallies.",
    fontClass: "font-aramaic",
    isRTL: true,
    tier: "core",
  },
  {
    name: "Classical Arabic",
    nativeName: "العربية الفصحى",
    sample: "ٱقْرَأْ بِٱسْمِ رَبِّكَ",
    translation: "“Recite in the name of your Lord” (Q 96:1)",
    script: "Early Qur’ānic rasm (dotless by default)",
    color: "from-emerald-500 to-teal-500",
    emoji: "🌙",
    description: "Language of the Qur’an, golden-age poetry, kalām, and early science across the Abbasid world.",
    topTenWorks: [
      "The Qur'an",
      "Mu'allaqat",
      "Kitab al-Aghani",
      "Muqaddimah",
      "Kalīla wa-Dimna",
      "One Thousand and One Nights",
      "Risalah (al-Shafi'i)",
      "Al-Jāmi' al-ṣaḥīḥ (al-Bukhari)",
      "Sībawayh's Kitāb",
      "The Ring of the Dove",
    ],
    writingInfo:
      "Strip vowel marks and, by default, suppress i‘jām (consonant dots) unless the witness includes them. No tatweel padding or Western punctuation; numerals spelled or abjad, never Arabic digits.",
    fontClass: "font-arabic",
    isRTL: true,
    tier: "core",
  },
  {
    name: "Classical Syriac",
    nativeName: "ܠܫܢܐ ܣܘܪܝܝܐ",
    sample: "ܒܫܡ ܐܠܗܐ ܚܝܐ",
    translation: "“In the name of the living God.”",
    script: "Estrangelā (default) with optional West/East Syriac toggles",
    color: "from-sky-500 to-indigo-600",
    emoji: "✝️",
    description: "Liturgical and literary language of Syriac Christianity—Peshitta, hymns, chronicles, and monastic rules.",
    topTenWorks: [
      "Peshitta",
      "Odes of Solomon",
      "Hymns on Paradise (Ephrem)",
      "Book of the Laws of the Countries",
      "Ecclesiastical History (John of Ephesus)",
      "Chronicle of Zuqnin",
      "Cause of Causes (Bar-Hebraeus)",
      "Julian Romance",
      "Cave of Treasures",
      "Book of the Bee",
    ],
    writingInfo:
      "Render Estrangelā right-to-left with vowel points off by default; only manuscript middle dots/paragraph signs for punctuation. Use overlines for numerals/abbreviations when attested; avoid later Serto letterforms unless required.",
    fontClass: "font-syriac",
    isRTL: true,
    tier: "core",
  },
  {
    name: "Old English",
    nativeName: "ᚫᛝᛚᛁᛋᚳ",
    sample: "HWÆTWEGARDENA",
    translation: "“Listen! We of the Spear-Danes…” (Beowulf incipit)",
    script: "Insular Latin capitals with þ, ð, æ, ƿ",
    color: "from-stone-400 to-stone-600",
    emoji: "🪢",
    description: "Beowulf, chronicles, homilies, and royal prefatory texts anchoring early English identity.",
    topTenWorks: [
      "Beowulf",
      "Anglo-Saxon Chronicle",
      "Cædmon's Hymn",
      "The Wanderer",
      "The Dream of the Rood",
      "The Seafarer",
      "Judith",
      "The Battle of Maldon",
      "Ælfric's Homilies",
      "Alfred's Preface to the Pastoral Care",
    ],
    writingInfo:
      "Use the Insular Latin inventory without j/u/w; embrace scriptio continua or sparse spacing, punctus/punctus elevatus only. Keep thorn, eth, ash, and wynn exactly as in witnesses; numerals Roman or spelled.",
    fontClass: "font-serif",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Yehudit (Paleo-Hebrew)",
    nativeName: "𐤉𐤄𐤅𐤃𐤉𐤕",
    sample: "𐤁𐤓𐤔𐤕",
    translation: "“Bereshit” – Genesis 1:1 in Paleo-Hebrew",
    script: "Paleo-Hebrew / Phoenician ductus",
    color: "from-yellow-500 to-amber-600",
    emoji: "🍎",
    description: "Pre-exilic inscriptions and ostraca—Gezer Calendar, Siloam Tunnel, Ketef Hinnom amulets.",
    topTenWorks: [
      "Gezer Calendar",
      "Siloam Inscription",
      "Mesha Stele",
      "Lachish Letters",
      "Ketef Hinnom Amulets",
      "Samaria Ostraca",
      "Arad Ostraca",
      "Amman Citadel Inscription",
      "Tel Zayit Abecedary",
      "Izbet Sartah Ostracon",
    ],
    writingInfo:
      "Use Paleo-Hebrew consonants, right-to-left, without niqqud or Masoretic marks. No Western punctuation; optional single dot divider only when a stone or ostracon shows it; numerals spelled out.",
    fontClass: "font-phoenician",
    isRTL: true,
    tier: "core",
  },
  {
    name: "Coptic (Sahidic)",
    nativeName: "ⲧⲙⲛ̄ⲧⲣⲙ̄ⲛ̄ⲕⲏⲙⲉ",
    sample: "ⲁⲩⲱ ⲛⲟⲩⲧⲉ ⲡⲉ",
    translation: "“And God is”",
    script: "Sahidic Coptic alphabet (Greek + Demotic letters)",
    color: "from-purple-400 to-indigo-500",
    emoji: "⚖️",
    description: "Monastic rules, Nag Hammadi codices, and desert father sayings that shaped late antique spirituality.",
    topTenWorks: [
      "Gospel of Thomas",
      "Pistis Sophia",
      "Life of Antony",
      "Shenoute's Canons",
      "Coptic Gospel of the Egyptians",
      "Nag Hammadi Library",
      "Apophthegmata Patrum",
      "Martyrdom of Saint Victor",
      "Gospel of Judas",
      "Pachomian Koinonia Rules",
    ],
    writingInfo:
      "Use Sahidic glyphs with supralinear strokes for nomina sacra. Punctuation is limited to ancient middots and paragraph marks; numerals via Greek-style letter values with overlines; avoid Arabic digits.",
    fontClass: "font-coptic",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Ancient Sumerian",
    nativeName: "𒅴𒂠",
    sample: "𒅴𒂠",
    translation: "Endonym for Sumer",
    script: "Cuneiform (left-to-right tablet lines)",
    color: "from-orange-700 to-amber-700",
    emoji: "🔆",
    description: "Earliest literature—Enheduanna hymns, king lists, law codes, lamentations, and epics from 3rd millennium BCE.",
    topTenWorks: [
      "Code of Ur-Nammu",
      "Sumerian King List",
      "Inanna’s Descent to the Netherworld",
      "Instructions of Shuruppak",
      "Lamentation over the Destruction of Ur",
      "Enmerkar and the Lord of Aratta",
      "Lugalbanda in the Mountain Cave",
      "Lugalbanda and the Anzud Bird",
      "Exaltation of Inanna",
      "Kesh Temple Hymn",
    ],
    writingInfo:
      "Render cuneiform signs exactly as tablets, left-to-right per line. Determinatives remain unmarked; use the small vertical wedge divider only when attested. Numerals follow sexagesimal tallies, never Arabic digits.",
    fontClass: "font-cuneiform",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Classical Tamil",
    nativeName: "சங்கத் தமிழ்",
    sample: "யாதும் ஊரே யாவரும் கேளீர்",
    translation: "\"Every town is our town; everyone is kin.\"",
    script: "Classical Tamil script with pulli/aytham controls",
    color: "from-pink-500 to-rose-600",
    emoji: "🪔",
    description: "Sangam poetry, epics, and grammatical treatises that anchor Dravidian literary history.",
    topTenWorks: [
      "Tolkāppiyam",
      "Tirukkuṟaḷ",
      "Cilappatikāram",
      "Manimekalai",
      "Ettuttokai",
      "Pattuppāṭṭu",
      "Civaka Cintamani",
      "Valayapathi",
      "Kundalakesi",
      "Iraiyanar Akapporul",
    ],
    writingInfo:
      "Use classical Tamil glyphs with pulli (virāma) and āytam exactly as sources show. Favor near scriptio continua; limit punctuation to traditional section marks; numerals spelled or rendered with Tamil digits only when attested.",
    fontClass: "font-tamil",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Akkadian",
    nativeName: "𒀝𒅗𒁺𒌑",
    sample: "𒀝𒅗𒁺𒌑",
    translation: "Endonym for Akkad",
    script: "Mesopotamian cuneiform (Old Babylonian and Assyrian hands)",
    color: "from-slate-500 to-slate-700",
    emoji: "🏹",
    description: "Gilgamesh, Enūma Eliš, Hammurabi’s Code, omen series, and state archives spanning two millennia.",
    topTenWorks: [
      "Epic of Gilgamesh",
      "Enūma Eliš",
      "Code of Hammurabi",
      "Atrahasis",
      "Descent of Ishtar",
      "Enūma Anu Enlil",
      "Babylonian Chronicles",
      "Cylinder of Cyrus",
      "Erra Epic",
      "Amarna Letters",
    ],
    writingInfo:
      "Write in Akkadian cuneiform, left-to-right per line. Keep Sumerograms/determinatives as uppercase transliteration would; wedge word-dividers only if present; numerals follow sexagesimal conventions.",
    fontClass: "font-cuneiform",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Vedic Sanskrit",
    nativeName: "𑀯𑁃𑀤𑀺𑀓 𑀲𑀁𑀲𑁆𑀓𑀾𑀢𑀫𑁆",
    sample: "𑀭𑁅 𑀯𑁃𑀤𑀺𑀓𑁆",
    translation: "“Truly Vedic”",
    script: "Brahmi with Vedic accent marks (toggle Grantha/Śāradā)",
    color: "from-yellow-400 to-lime-500",
    emoji: "🕉️",
    description: "Ṛgveda hymns, Brāhmaṇa prose, and Upaniṣadic philosophy—the oldest Indo-European corpus.",
    topTenWorks: [
      "Ṛgveda",
      "Bṛhadāraṇyaka Upaniṣad",
      "Chāndogya Upaniṣad",
      "Atharvaveda",
      "Aitareya Brāhmaṇa",
      "Śatapatha Brāhmaṇa",
      "Taittirīya Upaniṣad",
      "Kaṭha Upaniṣad",
      "Sāmaveda",
      "Yajurveda",
    ],
    writingInfo:
      "Default to Brahmi with required Vedic pitch accents. Offer Grantha/Śāradā toggles, but never modern Devanāgarī as the primary script. Only danda/double-danda punctuation; avagraha appears solely when manuscripts include it.",
    fontClass: "font-brahmi",
    isRTL: false,
    tier: "core",
  },
];
