/**
 * Language data structure with proper TypeScript typing
 * Sourced from docs/archive/imported-docs-from-main-repo/TOP_TEN_WORKS_PER_LANGUAGE.md
 */

export interface Language {
  name: string;
  nativeName: string;
  sample: string;
  translation: string;
  script: string;
  color: string;
  emoji: string;
  description: string;
  topTenWorks: string[];
  writingInfo: string;
  fontClass?: string; // CSS class for font-family
  isRTL?: boolean; // Right-to-left script
  tier: "top" | "core" | "partial";
}

export const languages: Language[] = [
  {
    name: "Classical Latin",
    nativeName: "LINGVA LATINA",
    sample: "ARMA·VIRVMQVE·CANO·TROIAE·QVI·PRIMVS·AB·ORIS",
    translation: "I sing of arms and the man, who first from the shores of Troy",
    script: "Roman capitals (A-Z without J/U/W)",
    color: "from-red-500 to-rose-600",
    emoji: "🏛️",
    description: "Most requested, foundational for Western education.",
    topTenWorks: [
      "Aeneid by Virgil",
      "Metamorphoses by Ovid",
      "De Rerum Natura by Lucretius",
      "Commentaries on the Gallic War by Julius Caesar",
      "Annals by Tacitus",
      "Ab Urbe Condita by Livy",
      "Odes by Horace",
      "Naturalis Historia by Pliny the Elder",
      "Satires by Juvenal",
      "Vulgate (Latin Bible) by Jerome",
    ],
    writingInfo:
      "Present text in Roman capitals with the classical inventory A B C D E F G H I K L M N O P Q R S T V X Y Z. Normalize input J→I, U→V, W→VV; map Æ/Œ→AE/OE. Use Y and Z primarily for Greek loans; Q occurs only as QV; retain K only where epigraphically fixed. Default to scriptio continua; optionally expose an \"Epigraphic divider\" toggle that inserts an interpunct (· U+00B7) as a word divider. Do not use macrons/breves; if vowel length must be surfaced, offer an \"apex mode\" using a combining acute. Numerals are Roman only with additive (IIII) or subtractive (IV) styles; prevent ligatures and any re-introduction of J/U/W or modern punctuation.",
    fontClass: "font-display",
    isRTL: false,
    tier: "top",
  },
  {
    name: "Koine Greek",
    nativeName: "ΚΟΙΝΗ ΔΙΑΛΕΚΤΟΣ",
    sample: "ΕΝΑΡΧΗΗΝΟΛΟΓΟΣΚΑΙΟΛΟΓΟΣΗΝΠΡΟΣΤΟΝΘΕΟΝ",
    translation: "In the beginning was the Word, and the Word was with God",
    script: "Greek capitals (scriptio continua, no accents)",
    color: "from-sky-500 to-indigo-500",
    emoji: "📖",
    description: "New Testament, Septuagint, Hellenistic philosophy.",
    topTenWorks: [
      "Septuagint (LXX)",
      "New Testament",
      "Jewish War by Flavius Josephus",
      "Parallel Lives by Plutarch",
      "Discourses & Enchiridion by Epictetus (via Arrian)",
      "Geographica by Strabo",
      "Almagest by Ptolemy",
      "On the Sublime (Pseudo-Longinus)",
      "Ecclesiastical History by Eusebius",
      "Anabasis of Alexander by Arrian",
    ],
    writingInfo:
      "Use the 24 Koine capitals (Α–Ω) with sigma as Σ only. Scriptio continua by default; allow inscriptional interpuncts when attested. Strip accents, breathings, and iota-subscripts; permit diaeresis only for genuine hiatus. Optional manuscript mode may overline nomina sacra. Numbers default to words, with optional Milesian numerals using stigma/koppa/sampi.",
    fontClass: "font-greek",
    isRTL: false,
    tier: "top",
  },
  {
    name: "Classical Greek",
    nativeName: "ΕΛΛΗΝΙΚΗ ΓΛΩΤΤΑ",
    sample: "ΜΗΝΙΝΑΕΙΔΕΘΕΑΠΗΛΗΙΑΔΕΩΑΧΙΛΗΟΣ",
    translation: "Sing, goddess, the wrath of Achilles, son of Peleus",
    script: "Greek capitals (Ionian/Eucleidean)",
    color: "from-blue-500 to-indigo-600",
    emoji: "🏺",
    description: "Homer, Plato, full Iliad with Perseus morphology.",
    topTenWorks: [
      "Iliad by Homer",
      "Odyssey by Homer",
      "Theogony by Hesiod",
      "Works and Days by Hesiod",
      "Oedipus Rex by Sophocles",
      "Antigone by Sophocles",
      "Medea by Euripides",
      "Histories by Herodotus",
      "History of the Peloponnesian War by Thucydides",
      "Republic by Plato",
    ],
    writingInfo:
      "Encode the 24 Ionian/Eucleidean capitals (Α–Ω) with sigma strictly as Σ—never lunate. Default to scriptio continua with optional interpuncts only when witnesses show them. Omit accents, breathings, and iota-subscripts; rely on fonts for uncial forms. Numerals follow Milesian or Attic systems as attested; no Arabic digits.",
    fontClass: "font-greek",
    isRTL: false,
    tier: "top",
  },
  {
    name: "Biblical Hebrew",
    nativeName: "יהודית",
    sample: "בראשית ברא אלהים את השמים ואת הארץ",
    translation: "In the beginning God created the heavens and the earth",
    script: "Unpointed square Hebrew",
    color: "from-amber-500 to-yellow-600",
    emoji: "🕎",
    description: "Torah, Prophets, Writings, theological studies.",
    topTenWorks: [
      "Genesis (Bereshit)",
      "Exodus (Shemot)",
      "Isaiah (Yeshayahu)",
      "Psalms (Tehillim)",
      "Deuteronomy (Devarim)",
      "Samuel (Shmuel)",
      "Kings (Melakhim)",
      "Jeremiah (Yirmeyahu)",
      "Ezekiel (Yehezkel)",
      "Job (Iyov)",
    ],
    writingInfo:
      "Use unpointed square Hebrew (Ketav Ashuri) right-to-left. Remove niqqud, te'amim, maqaf, sof pasuq, and modern punctuation unless the witness includes them. Separate words with simple spacing, keep matres lectionis as written, and spell numerals per the source.",
    fontClass: "font-hebrew",
    isRTL: true,
    tier: "top",
  },
  {
    name: "Classical Sanskrit",
    nativeName: "संस्कृतम्",
    sample: "धर्मक्षेत्रेकुरुक्षेत्रेसमवेतायुयुत्सवः",
    translation: "Gathered to fight on the field of dharma, the field of the Kurus",
    script: "Devanagari with full ligatures",
    color: "from-orange-500 to-red-600",
    emoji: "🪷",
    description: "Mahābhārata, Bhagavad-Gītā, Upaniṣads.",
    topTenWorks: [
      "Mahābhārata (incl. Bhagavad-Gītā)",
      "Rāmāyaṇa",
      "Bhagavad-Gītā",
      "Arthaśāstra (Kauṭilya)",
      "Aṣṭādhyāyī (Pāṇini)",
      "Abhijñānaśākuntalam (Kālidāsa)",
      "Meghadūta (Kālidāsa)",
      "Suśruta-saṁhitā",
      "Pañcatantra",
      "Yoga Sūtras of Patañjali",
    ],
    writingInfo:
      "Use Devanagari (or early Nāgarī) with full conjunct ligatures and scriptio continua. End sections only with danda or double danda (U+0964/U+0965); no Western punctuation. Remove editorial hyphens, allow avagraha (ऽ) only when attested, and spell numerals per the witness.",
    fontClass: "font-devanagari",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Classical Chinese",
    nativeName: "文言文",
    sample: "子曰學而時習之不亦說乎",
    translation: "The Master said: To learn and practice at the proper time—is that not a joy?",
    script: "Traditional Han characters, vertical columns right-to-left",
    color: "from-amber-400 to-emerald-500",
    emoji: "🐉",
    description: "Analects, Dao De Jing, classical poetry and statecraft texts.",
    topTenWorks: [
      "Analects of Confucius",
      "Dao De Jing (Laozi)",
      "The Art of War (Sun Tzu)",
      "Zhuangzi",
      "Records of the Grand Historian (Sima Qian)",
      "Mencius",
      "I Ching (Book of Changes)",
      "Classic of Poetry (Shijing)",
      "Book of Documents (Shujing)",
      "Zuo Zhuan",
    ],
    writingInfo:
      "Use traditional Hanzi without punctuation or spaces; default layout is vertical columns running top-to-bottom and ordered right-to-left. Do not normalize variant graphs or convert to simplified; numerals remain in Chinese characters (一二三…) and editorial marks like 、，。 appear only if attested in the witness.",
    fontClass: "font-cjk",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Old Church Slavonic",
    nativeName: "ⰔⰎⱁⰲⱑⰐⰟⰴⰟ ⱑⰸⱏⰽⰟ",
    sample: "ⰔⰎⱁⰲⱑⰐⰟⰴⰟ ⱑⰸⱏⰽⰟ",
    translation: "The Slavonic tongue",
    script: "Early Glagolitic uncial (with Cyrillic ustav as fallback)",
    color: "from-purple-500 to-fuchsia-600",
    emoji: "☦️",
    description: "Glagolitic and early Cyrillic liturgical language, foundation of Slavic culture.",
    topTenWorks: [
      "Codex Zographensis (Gospels)",
      "Ostromir Gospel",
      "Sinai Psalter",
      "Proglas (Prologue to the Gospels)",
      "Lives of Cyril and Methodius",
      "Euchologium Sinaiticum",
      "Didactic Gospel (Constantine of Preslav)",
      "Svyatoslav's Miscellany",
      "Codex Marianus (Gospels)",
      "Kievan Glagolitic Sheets",
    ],
    writingInfo:
      "Prefer Glagolitic uncial for earliest witnesses; if Cyrillic, use early ustav with full yats/yers/izhitsa/fita inventory. No lowercase; keep titlo for nomina sacra and numeral letters. Use only ancient middle/high dots and paragraph marks for punctuation. Numbers are letters with titlo; never Arabic digits; retain yers (Ъ/Ь) and nasal vowels (Ѧ/Ѫ) exactly as written.",
    fontClass: "font-glagolitic",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Old Norse (Norrœnt mál)",
    nativeName: "ᚢᛚᚠᛁᛏ",
    sample: "GANGASKALSKYLIGUMNASON",
    translation: "A son of men must venture forth",
    script: "Medieval Latin script with þ/ð/æ",
    color: "from-emerald-500 to-lime-600",
    emoji: "🪓",
    description: "Viking Age sagas, Poetic Edda.",
    topTenWorks: [
      "Poetic Edda",
      "Prose Edda (Snorri Sturluson)",
      "Völsunga saga",
      "Egil's Saga",
      "Hávamál",
      "Njál's saga",
      "Laxdæla saga",
      "Heimskringla",
      "Grettir's Saga",
      "Eiríks saga rauða",
    ],
    writingInfo:
      "Use 12th–13th c. Icelandic/Norwegian Latin-script conventions: a b c d e f g h i k l m n o p q r s t u/v x y z plus þ, ð, æ, ǫ per witness. No lowercase distinction; avoid modern punctuation—only punctus, punctus elevatus/interrogativus where attested. Use tironian et (⁊) for “ok” when sources do, keep spellings unnormalized, and render numbers as Roman or spelled per the manuscript (never Arabic digits).",
    fontClass: "font-serif",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Middle Egyptian",
    nativeName: "𓂋𓈖𓎡𓅓𓏏",
    sample: "𓇋𓈖𓂓𓅱𓈙𓅱𓏏𓈖𓇋",
    translation: "I was Sinuhe",
    script: "Egyptian hieroglyphs",
    color: "from-yellow-600 to-amber-700",
    emoji: "👁️",
    description: "Tale of Sinuhe, Book of the Dead (2000-1300 BCE).",
    topTenWorks: [
      "Story of Sinuhe",
      "Coffin Texts",
      "Tale of the Shipwrecked Sailor",
      "Instruction of King Merikare",
      "Instruction of Amenemope",
      "Book of the Dead",
      "Prophecy of Neferti",
      "Report of Wenamun",
      "Merneptah Stele (Israel Stele)",
      "Shabaka Stone (Memphite Theology)",
    ],
    writingInfo:
      "Use Middle Egyptian hieroglyphs with canonical grouping, lines running right-to-left (or vertical) with signs facing right. No vowels, spaces, or modern punctuation; preserve determinatives/logograms exactly and omit editorial brackets. Use hieratic only when the witness demands it, and render numerals in hieroglyphic tallies.",
    fontClass: "font-serif", // Fallback – dedicated hieroglyph font handled where available
    isRTL: false,
    tier: "core",
  },
  {
    name: "Pali",
    nativeName: "𑀧𑀸𑀮𑀺",
    sample: "𑀤𑀫𑁆𑀧𑀸𑀤𑀸",
    translation: "Dhammapada (rendered in Brahmi)",
    script: "Asokan Brahmi (Sinhala toggle for palm-leaf witnesses)",
    color: "from-amber-500 to-orange-600",
    emoji: "☸️",
    description: "Theravada canon preserved in Sri Lanka and Southeast Asia; earliest stratum of the Buddha’s teachings.",
    topTenWorks: [
      "Dīgha Nikāya",
      "Majjhima Nikāya",
      "Dhammapada",
      "Jātaka Tales",
      "Visuddhimagga (Buddhaghosa)",
      "Saṃyutta Nikāya",
      "Aṅguttara Nikāya",
      "Milinda Pañha",
      "Vinaya Piṭaka",
      "Mahāvaṃsa",
    ],
    writingInfo:
      "Default to Asokan Brahmi with a selectable Sinhala hand; forbid Western punctuation—only danda and double-danda. Avoid later Devanāgarī, preserve matres lectionis, sandhi, and ligatures exactly as witnessed.",
    fontClass: "font-brahmi",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Ancient Aramaic",
    nativeName: "𐡀𐡓𐡌𐡉𐡕",
    sample: "𐡁𐡓𐡀 𐡀𐡋𐡄𐡉𐡌",
    translation: "“Created by Elohim” (Genesis in Imperial Aramaic)",
    script: "Imperial Aramaic consonantal alphabet",
    color: "from-rose-500 to-red-500",
    emoji: "🗣️",
    description: "Lingua franca of the Near East—imperial decrees, Dead Sea Scrolls, Elephantine papyri, and targumim.",
    topTenWorks: [
      "Wisdom of Ahiqar",
      "Targum Onkelos",
      "Genesis Apocryphon (1Q20)",
      "Book of Daniel (Aramaic chapters)",
      "Book of Ezra (Aramaic sections)",
      "Elephantine Papyri",
      "Zakkur Stele",
      "Tel Dan Stele",
      "Peshitta",
      "Aramaic Incantation Bowls",
    ],
    writingInfo:
      "Use Imperial Aramaic, right-to-left, with no vowel pointing or Western punctuation. Word dividers only where inscriptions show dots, otherwise scriptio continua; numerals spelled or rendered with stroke tallies.",
    fontClass: "font-aramaic",
    isRTL: true,
    tier: "core",
  },
  {
    name: "Classical Arabic",
    nativeName: "العربية الفصحى",
    sample: "ٱقْرَأْ بِٱسْمِ رَبِّكَ",
    translation: "“Recite in the name of your Lord” (Q 96:1)",
    script: "Early Qur’ānic rasm (dotless by default)",
    color: "from-emerald-500 to-teal-500",
    emoji: "🌙",
    description: "Language of the Qur’an, golden-age poetry, kalām, and early science across the Abbasid world.",
    topTenWorks: [
      "The Qur'an",
      "Mu'allaqat",
      "Kitab al-Aghani",
      "Muqaddimah",
      "Kalīla wa-Dimna",
      "One Thousand and One Nights",
      "Risalah (al-Shafi'i)",
      "Al-Jāmi' al-ṣaḥīḥ (al-Bukhari)",
      "Sībawayh's Kitāb",
      "The Ring of the Dove",
    ],
    writingInfo:
      "Strip vowel marks and, by default, suppress i‘jām (consonant dots) unless the witness includes them. No tatweel padding or Western punctuation; numerals spelled or abjad, never Arabic digits.",
    fontClass: "font-arabic",
    isRTL: true,
    tier: "core",
  },
  {
    name: "Classical Syriac",
    nativeName: "ܠܫܢܐ ܣܘܪܝܝܐ",
    sample: "ܒܫܡ ܐܠܗܐ ܚܝܐ",
    translation: "“In the name of the living God.”",
    script: "Estrangelā (default) with optional West/East Syriac toggles",
    color: "from-sky-500 to-indigo-600",
    emoji: "✝️",
    description: "Liturgical and literary language of Syriac Christianity—Peshitta, hymns, chronicles, and monastic rules.",
    topTenWorks: [
      "Peshitta",
      "Odes of Solomon",
      "Hymns on Paradise (Ephrem)",
      "Book of the Laws of the Countries",
      "Ecclesiastical History (John of Ephesus)",
      "Chronicle of Zuqnin",
      "Cause of Causes (Bar-Hebraeus)",
      "Julian Romance",
      "Cave of Treasures",
      "Book of the Bee",
    ],
    writingInfo:
      "Render Estrangelā right-to-left with vowel points off by default; only manuscript middle dots/paragraph signs for punctuation. Use overlines for numerals/abbreviations when attested; avoid later Serto letterforms unless required.",
    fontClass: "font-syriac",
    isRTL: true,
    tier: "core",
  },
  {
    name: "Old English",
    nativeName: "ᚫᛝᛚᛁᛋᚳ",
    sample: "HWÆTWEGARDENA",
    translation: "“Listen! We of the Spear-Danes…” (Beowulf incipit)",
    script: "Insular Latin capitals with þ, ð, æ, ƿ",
    color: "from-stone-400 to-stone-600",
    emoji: "🪢",
    description: "Beowulf, chronicles, homilies, and royal prefatory texts anchoring early English identity.",
    topTenWorks: [
      "Beowulf",
      "Anglo-Saxon Chronicle",
      "Cædmon's Hymn",
      "The Wanderer",
      "The Dream of the Rood",
      "The Seafarer",
      "Judith",
      "The Battle of Maldon",
      "Ælfric's Homilies",
      "Alfred's Preface to the Pastoral Care",
    ],
    writingInfo:
      "Use the Insular Latin inventory without j/u/w; embrace scriptio continua or sparse spacing, punctus/punctus elevatus only. Keep thorn, eth, ash, and wynn exactly as in witnesses; numerals Roman or spelled.",
    fontClass: "font-serif",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Yehudit (Paleo-Hebrew)",
    nativeName: "𐤉𐤄𐤅𐤃𐤉𐤕",
    sample: "𐤁𐤓𐤔𐤕",
    translation: "“Bereshit” – Genesis 1:1 in Paleo-Hebrew",
    script: "Paleo-Hebrew / Phoenician ductus",
    color: "from-yellow-500 to-amber-600",
    emoji: "🍎",
    description: "Pre-exilic inscriptions and ostraca—Gezer Calendar, Siloam Tunnel, Ketef Hinnom amulets.",
    topTenWorks: [
      "Gezer Calendar",
      "Siloam Inscription",
      "Mesha Stele",
      "Lachish Letters",
      "Ketef Hinnom Amulets",
      "Samaria Ostraca",
      "Arad Ostraca",
      "Amman Citadel Inscription",
      "Tel Zayit Abecedary",
      "Izbet Sartah Ostracon",
    ],
    writingInfo:
      "Use Paleo-Hebrew consonants, right-to-left, without niqqud or Masoretic marks. No Western punctuation; optional single dot divider only when a stone or ostracon shows it; numerals spelled out.",
    fontClass: "font-phoenician",
    isRTL: true,
    tier: "core",
  },
  {
    name: "Coptic (Sahidic)",
    nativeName: "ⲧⲙⲛ̄ⲧⲣⲙ̄ⲛ̄ⲕⲏⲙⲉ",
    sample: "ⲁⲩⲱ ⲛⲟⲩⲧⲉ ⲡⲉ",
    translation: "“And God is”",
    script: "Sahidic Coptic alphabet (Greek + Demotic letters)",
    color: "from-purple-400 to-indigo-500",
    emoji: "⚖️",
    description: "Monastic rules, Nag Hammadi codices, and desert father sayings that shaped late antique spirituality.",
    topTenWorks: [
      "Gospel of Thomas",
      "Pistis Sophia",
      "Life of Antony",
      "Shenoute's Canons",
      "Coptic Gospel of the Egyptians",
      "Nag Hammadi Library",
      "Apophthegmata Patrum",
      "Martyrdom of Saint Victor",
      "Gospel of Judas",
      "Pachomian Koinonia Rules",
    ],
    writingInfo:
      "Use Sahidic glyphs with supralinear strokes for nomina sacra. Punctuation is limited to ancient middots and paragraph marks; numerals via Greek-style letter values with overlines; avoid Arabic digits.",
    fontClass: "font-coptic",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Ancient Sumerian",
    nativeName: "𒅴𒂠",
    sample: "𒅴𒂠",
    translation: "Endonym for Sumer",
    script: "Cuneiform (left-to-right tablet lines)",
    color: "from-orange-700 to-amber-700",
    emoji: "🔆",
    description: "Earliest literature—Enheduanna hymns, king lists, law codes, lamentations, and epics from 3rd millennium BCE.",
    topTenWorks: [
      "Code of Ur-Nammu",
      "Sumerian King List",
      "Inanna’s Descent to the Netherworld",
      "Instructions of Shuruppak",
      "Lamentation over the Destruction of Ur",
      "Enmerkar and the Lord of Aratta",
      "Lugalbanda in the Mountain Cave",
      "Lugalbanda and the Anzud Bird",
      "Exaltation of Inanna",
      "Kesh Temple Hymn",
    ],
    writingInfo:
      "Render cuneiform signs exactly as tablets, left-to-right per line. Determinatives remain unmarked; use the small vertical wedge divider only when attested. Numerals follow sexagesimal tallies, never Arabic digits.",
    fontClass: "font-cuneiform",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Classical Tamil",
    nativeName: "சங்கத் தமிழ்",
    sample: "யாதும் ஊரே யாவரும் கேளீர்",
    translation: "\"Every town is our town; everyone is kin.\"",
    script: "Classical Tamil script with pulli/aytham controls",
    color: "from-pink-500 to-rose-600",
    emoji: "🪔",
    description: "Sangam poetry, epics, and grammatical treatises that anchor Dravidian literary history.",
    topTenWorks: [
      "Tolkāppiyam",
      "Tirukkuṟaḷ",
      "Cilappatikāram",
      "Manimekalai",
      "Ettuttokai",
      "Pattuppāṭṭu",
      "Civaka Cintamani",
      "Valayapathi",
      "Kundalakesi",
      "Iraiyanar Akapporul",
    ],
    writingInfo:
      "Use classical Tamil glyphs with pulli (virāma) and āytam exactly as sources show. Favor near scriptio continua; limit punctuation to traditional section marks; numerals spelled or rendered with Tamil digits only when attested.",
    fontClass: "font-tamil",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Akkadian",
    nativeName: "𒀝𒅗𒁺𒌑",
    sample: "𒀝𒅗𒁺𒌑",
    translation: "Endonym for Akkad",
    script: "Mesopotamian cuneiform (Old Babylonian and Assyrian hands)",
    color: "from-slate-500 to-slate-700",
    emoji: "🏹",
    description: "Gilgamesh, Enūma Eliš, Hammurabi’s Code, omen series, and state archives spanning two millennia.",
    topTenWorks: [
      "Epic of Gilgamesh",
      "Enūma Eliš",
      "Code of Hammurabi",
      "Atrahasis",
      "Descent of Ishtar",
      "Enūma Anu Enlil",
      "Babylonian Chronicles",
      "Cylinder of Cyrus",
      "Erra Epic",
      "Amarna Letters",
    ],
    writingInfo:
      "Write in Akkadian cuneiform, left-to-right per line. Keep Sumerograms/determinatives as uppercase transliteration would; wedge word-dividers only if present; numerals follow sexagesimal conventions.",
    fontClass: "font-cuneiform",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Vedic Sanskrit",
    nativeName: "𑀯𑁃𑀤𑀺𑀓 𑀲𑀁𑀲𑁆𑀓𑀾𑀢𑀫𑁆",
    sample: "𑀭𑁅 𑀯𑁃𑀤𑀺𑀓𑁆",
    translation: "“Truly Vedic”",
    script: "Brahmi with Vedic accent marks (toggle Grantha/Śāradā)",
    color: "from-yellow-400 to-lime-500",
    emoji: "🕉️",
    description: "Ṛgveda hymns, Brāhmaṇa prose, and Upaniṣadic philosophy—the oldest Indo-European corpus.",
    topTenWorks: [
      "Ṛgveda",
      "Bṛhadāraṇyaka Upaniṣad",
      "Chāndogya Upaniṣad",
      "Atharvaveda",
      "Aitareya Brāhmaṇa",
      "Śatapatha Brāhmaṇa",
      "Taittirīya Upaniṣad",
      "Kaṭha Upaniṣad",
      "Sāmaveda",
      "Yajurveda",
    ],
    writingInfo:
      "Default to Brahmi with required Vedic pitch accents. Offer Grantha/Śāradā toggles, but never modern Devanāgarī as the primary script. Only danda/double-danda punctuation; avagraha appears solely when manuscripts include it.",
    fontClass: "font-brahmi",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Classical Armenian",
    nativeName: "ԳՐԱԲԱՐ",
    sample: "ԵՎ ԷԱՌ ԶԱՌՆՍԴՈԹՆԻԹՏՈՒՏԵԱՆ",
    translation: "And he took the bread and gave thanks",
    script: "Classical Armenian alphabet (Mesrop Mashtots, 405 AD)",
    color: "from-red-600 to-orange-600",
    emoji: "🦅",
    description: "Grabar, the liturgical and literary language of Armenian Christianity, history, and medieval scholarship.",
    topTenWorks: [
      "History of Armenia by Movses Khorenatsi",
      "Book of Lamentations by Gregory of Narek",
      "Life of Mashtots by Koriwn",
      "History of the Armenians by Agathangelos",
      "Epic Histories by Pavstos Buzand",
      "Geography by Anania Shirakatsi",
      "Against the Sects by Eznik of Kolb",
      "Armenian Bible (5th century translation)",
      "Hymns by Nerses Shnorhali",
      "Fables of Mkhitar Gosh",
    ],
    writingInfo:
      "Use the 36-letter Mesropian Armenian alphabet in majuscule (erkatagir) or minuscule (bolorgir) per witness period. Maintain ligatures, no modern punctuation except attested manuscript marks. Numbers use Armenian letter-numerals with titlo; never Arabic digits. Keep scriptio continua or sparse spacing per manuscript.",
    fontClass: "font-armenian",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Hittite",
    nativeName: "𒌷𒉌𒅆𒇷",
    sample: "𒀀𒉌𒋫𒀸𒅗𒀸",
    translation: "Anitta the king (from the oldest Indo-European text)",
    script: "Anatolian cuneiform adapted from Akkadian",
    color: "from-stone-600 to-amber-800",
    emoji: "🐂",
    description: "Earliest attested Indo-European language, royal annals and treaties from the Hittite Empire (c. 1650–1180 BCE).",
    topTenWorks: [
      "Anitta Text",
      "Telepinu Proclamation",
      "Treaty of Kadesh",
      "Songs of Ullikummi",
      "Song of Hedammu",
      "Hittite Laws",
      "Annals of Mursili II",
      "Apology of Hattusili III",
      "Plague Prayers of Mursili II",
      "Ritual of Tunnawi",
    ],
    writingInfo:
      "Render Anatolian cuneiform signs left-to-right per line. Preserve Sumerograms and Akkadograms as uppercase transliteration would show; determinatives unmarked. Use word-dividers only when tablet shows them. Numerals follow sexagesimal conventions, never Arabic digits.",
    fontClass: "font-cuneiform",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Old Egyptian (Old Kingdom)",
    nativeName: "𓂋𓈖𓎡𓅓𓏏𓀀",
    sample: "𓊪𓏏𓎛𓇯𓀭",
    translation: "Ptah-Hotep (Instruction of Ptah-Hotep)",
    script: "Old Kingdom hieroglyphs (2686–2181 BCE)",
    color: "from-yellow-700 to-orange-800",
    emoji: "🪲",
    description: "Language of the Pyramid Age—royal decrees, wisdom literature, and the earliest Pyramid Texts.",
    topTenWorks: [
      "Pyramid Texts (Unas, Teti, Pepi I & II)",
      "Instruction of Ptahhotep",
      "Autobiography of Weni",
      "Palermo Stone (Royal Annals)",
      "Autobiography of Harkhuf",
      "Maxims of Ptahhotep",
      "Instruction of Kagemni",
      "Pyramid Text Spell 273-274 (Cannibal Hymn)",
      "Autobiography of Pepinakht",
      "Abusir Papyri",
    ],
    writingInfo:
      "Use Old Kingdom hieroglyphs with traditional grouping, lines usually right-to-left (signs face right), occasionally vertical. No vowels, spaces, or modern punctuation. Preserve logograms and determinatives exactly; omit editorial brackets. Numerals in hieroglyphic tallies only.",
    fontClass: "font-serif",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Avestan",
    nativeName: "𐬀𐬎𐬞𐬀𐬌𐬙𐬌",
    sample: "𐬀𐬚𐬀𐬵𐬎𐬨𐬀𐬰𐬛𐬁",
    translation: "Ahura Mazda (from the Gathas)",
    script: "Avestan alphabet (invented c. 400–500 CE for Sassanian transcription)",
    color: "from-orange-600 to-red-700",
    emoji: "🔥",
    description: "Sacred language of Zoroastrianism—Gathas of Zarathustra, Yasna liturgy, and Vendidad law code.",
    topTenWorks: [
      "Gathas (Yasna 28–34, 43–51, 53)",
      "Yasna (72 chapters)",
      "Visperad",
      "Vendidad",
      "Yashts (hymns to yazatas)",
      "Khordeh Avesta",
      "Nirangistan",
      "Herbedestan",
      "Aogemadaecha",
      "Hādōkht Nask",
    ],
    writingInfo:
      "Use the comprehensive Avestan script, right-to-left. Strip modern punctuation—only danda and double-danda where attested. Old Avestan (Gathic) differs from Young Avestan orthographically; maintain witness-specific conventions. Numerals spelled or rendered per manuscript tradition.",
    fontClass: "font-avestan",
    isRTL: true,
    tier: "core",
  },
  {
    name: "Classical Nahuatl",
    nativeName: "NĀHUATLAHTOLLI",
    sample: "INCIPIUHQUIAMOXTLI",
    translation: "Here begins the book (Florentine Codex opening)",
    script: "Latin alphabet (post-conquest); pictographic codices pre-1521",
    color: "from-amber-700 to-red-600",
    emoji: "🐆",
    description: "Language of the Aztec Empire—epic poetry, historical annals, and the encyclopedic Florentine Codex.",
    topTenWorks: [
      "Florentine Codex (Sahagún)",
      "Cantares Mexicanos",
      "Codex Mendoza",
      "Annals of Tlatelolco",
      "Romances de los Señores de la Nueva España",
      "Codex Xolotl",
      "Historia Tolteca-Chichimeca",
      "Codex Chimalpopoca",
      "Huei tlamahuiçoltica",
      "Nican Mopohua",
    ],
    writingInfo:
      "Use Classical Nahuatl orthography with macrons for long vowels (ā, ē, ī, ō) and saltillo <h>. Maintain glottal stop markers, avoid modern Spanish conventions. Numerals spelled or rendered with Aztec bar-and-dot notation when attested. No Western punctuation unless witness includes it.",
    fontClass: "font-serif",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Classical Tibetan",
    nativeName: "བོད་ཡིག",
    sample: "ཨོཾ་མ་ཎི་པདྨེ་ཧཱུྃ",
    translation: "Om mani padme hum (six-syllable mantra)",
    script: "Tibetan Uchen (དབུ་ཅན་) – formal block script",
    color: "from-orange-500 to-red-600",
    emoji: "🏔️",
    description: "Canonical language of Tibetan Buddhism—Kangyur, Tengyur, and centuries of commentary preserving Sanskrit originals.",
    topTenWorks: [
      "Kangyur (Buddha's words, 108 volumes)",
      "Tengyur (commentaries, 225 volumes)",
      "Bardo Thodol (Tibetan Book of the Dead)",
      "Jewel Ornament of Liberation (Gampopa)",
      "Bodhicharyavatara (Shantideva, Tibetan trans.)",
      "Madhyamakavatara (Chandrakirti, Tibetan trans.)",
      "Lamrim Chenmo (Tsongkhapa)",
      "Treasury of Abhidharma (Vasubandhu, Tibetan trans.)",
      "Blue Annals",
      "Gesar Epic",
    ],
    writingInfo:
      "Use Uchen script with full stacks and subscript/superscript letters. No spaces between syllables; tsheg (་) marks syllable boundaries. Section breaks use shad (།) and double shad (༎). Numerals in Tibetan digits (༠-༩) or spelled per witness. Avoid modern Western punctuation; preserve traditional manuscript conventions.",
    fontClass: "font-tibetan",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Old Japanese",
    nativeName: "ヤマトコトバ",
    sample: "コキキフトノリトコト",
    translation: "Kojiki and Norito, ancient words (Man'yōgana approximation)",
    script: "Man'yōgana (万葉仮名) – Chinese characters used phonetically",
    color: "from-pink-600 to-red-600",
    emoji: "🗻",
    description: "Language of Nara-period Japan (710–794)—Kojiki mythology, Nihon Shoki chronicles, and Man'yōshū poetry.",
    topTenWorks: [
      "Kojiki (712)",
      "Nihon Shoki (720)",
      "Man'yōshū (c. 759)",
      "Fudoki (regional gazetteers)",
      "Kaifūsō (poetic anthology, 751)",
      "Norito (Shinto liturgies)",
      "Senmyō (imperial edicts)",
      "Kogoshūi",
      "Harima-no-kuni Fudoki",
      "Izumo-no-kuni Fudoki",
    ],
    writingInfo:
      "Use Man'yōgana—one Chinese character per Old Japanese syllable (mora). No spaces or punctuation unless witness shows them. Keep variant character choices per manuscript tradition. Numerals in kanji (一二三…) or spelled. Avoid later kana; strict phonetic use of Han characters only.",
    fontClass: "font-cjk",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Classical Quechua",
    nativeName: "RUNA SIMI",
    sample: "KAYPACHA",
    translation: "This world (Quechua cosmology term)",
    script: "Latin alphabet (post-conquest); quipu (knotted strings) pre-1533",
    color: "from-yellow-600 to-orange-700",
    emoji: "🦙",
    description: "Lingua franca of the Inca Empire—oral epics, administrative records, and early colonial catechisms.",
    topTenWorks: [
      "Doctrina Christiana (1584, first printed Quechua)",
      "Vocabulario de la lengua general (González Holguín, 1608)",
      "Grammatica o arte (Domingo de Santo Tomás, 1560)",
      "Ollantay (drama)",
      "Apu Inca Atawallpaman (elegy)",
      "Huarochirí Manuscript",
      "Third Council of Lima Catechism (1583)",
      "Suma y narración de los Incas (Betanzos)",
      "Relación de Antiguedades (Pachacuti Yamqui)",
      "Quechua Hymns (colonial religious poetry)",
    ],
    writingInfo:
      "Use colonial orthography with three-vowel system (a, i, u), aspirated stops (p', t', ch', k', q'), and ejectives (ph, th, chh, kh, qh). Distinguish uvular /q/ from velar /k/. No glottalization markers; avoid modern five-vowel spelling. Numerals spelled or Inca decimal system when attested.",
    fontClass: "font-serif",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Middle Persian (Pahlavi)",
    nativeName: "𐭯𐭠𐭫𐭮𐭩𐭢",
    sample: "𐭠𐭥𐭧𐭥𐭬𐭦𐭣",
    translation: "Ohrmazd (Ahura Mazda in Middle Persian)",
    script: "Book Pahlavi – Aramaic-derived cursive script",
    color: "from-amber-600 to-orange-700",
    emoji: "🪙",
    description: "Official language of Sassanian Persia and Zoroastrian religious texts—Denkard, Bundahishn, Arda Viraf.",
    topTenWorks: [
      "Denkard (9th–10th c. encyclopedia)",
      "Bundahishn (Zoroastrian cosmogony)",
      "Arda Viraf Namag",
      "Khwaday-Namag (Book of Lords)",
      "Karnamag i Ardashir i Pabagan",
      "Draxt Asurig (Assyrian Tree debate)",
      "Ayādgār ī Zarērān",
      "Menog-i Khrad (Spirit of Wisdom)",
      "Wizīdagīhā ī Zādspram",
      "Pahlavi Rivayat",
    ],
    writingInfo:
      "Use Book Pahlavi with Aramaic logograms (ideograms) for common words; phonetic spelling for rest. Right-to-left, no vowel pointing unless manuscript includes it. Only manuscript punctuation (dots, paragraph marks). Numerals via Aramaic word-signs or spelled; never Arabic digits.",
    fontClass: "font-pahlavi",
    isRTL: true,
    tier: "core",
  },
  {
    name: "Old Irish",
    nativeName: "GOÍDELC",
    sample: "BENDACHTCÚ",
    translation: "Blessings (early Irish greeting)",
    script: "Insular Latin majuscule; Ogham for inscriptions",
    color: "from-green-600 to-emerald-700",
    emoji: "☘️",
    description: "Language of early medieval Ireland—Táin Bó Cúailnge, monastic annals, Brehon law, and Ogham stones.",
    topTenWorks: [
      "Táin Bó Cúailnge",
      "Lebor Gabála Érenn",
      "Immram Brain (Voyage of Bran)",
      "Togail Bruidne Dá Derga",
      "Cath Maige Tuired",
      "Audacht Morainn",
      "Críth Gablach (law text)",
      "Félire Óengusso (martyrology)",
      "Old Irish Glosses (Milan, Würzburg, St. Gall)",
      "Saltair na Rann",
    ],
    writingInfo:
      "Use Insular majuscule without j/k/v/w/y/z. Lenition shown by superdot (ḟ, ṡ) or h-digraph per manuscript. Keep punctus, punctus elevatus; avoid modern punctuation. Ogham inscriptions: vertical stemline, strokes/notches for consonants and vowels. Numerals Roman or spelled.",
    fontClass: "font-serif",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Gothic",
    nativeName: "𐌲𐌿𐍄𐌹𐍃𐌺",
    sample: "𐌹𐌽𐌰𐍂𐌷𐌰𐍂𐌽𐌰𐍅𐌰𐍃𐍅𐌰𐌿𐍂𐌳",
    translation: "In the beginning was the Word (John 1:1, Wulfila Bible)",
    script: "Gothic alphabet (invented by Wulfila, c. 350 AD)",
    color: "from-gray-600 to-slate-700",
    emoji: "⚔️",
    description: "Earliest attested Germanic literary language—Wulfila's Bible translation, Codex Argenteus (Silver Bible).",
    topTenWorks: [
      "Codex Argenteus (Gospels)",
      "Codex Ambrosianus A (Pauline Epistles)",
      "Codex Ambrosianus B (Pauline Epistles)",
      "Codex Carolinus (Romans fragments)",
      "Codex Gissensis (Luke fragments)",
      "Skeireins (Commentary on John)",
      "Gothic Calendar (fragmentary)",
      "Codex Ambrosianus E (Nehemiah 5–7)",
      "Bologna Fragment (Galatians)",
      "Codex Taurinensis (Galatians fragments)",
    ],
    writingInfo:
      "Use Wulfila's Gothic alphabet (27 letters derived from Greek/Latin/Runic). Left-to-right, maintain manuscript abbreviations and nomina sacra conventions. Punctuation limited to ancient middots and section marks. Numerals via Greek-style letter-values with overlines; avoid Arabic digits.",
    fontClass: "font-gothic",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Geʽez",
    nativeName: "ግዕዝ",
    sample: "ብስረተወንገልየእግዚእነየሱስክርስቶስ",
    translation: "The gospel of our Lord Jesus Christ (Ethiopic Bible opening)",
    script: "Geʽez fidäl (Ethiopic abugida)",
    color: "from-amber-600 to-yellow-700",
    emoji: "🦁",
    description: "Classical language of Ethiopia—Kebra Nagast, Ethiopic Bible, monastic rules, and liturgical hymns.",
    topTenWorks: [
      "Kebra Nagast (Glory of Kings)",
      "Ethiopic Bible (Ge'ez translation)",
      "Book of Enoch (complete Ge'ez text)",
      "Physiologus (Ethiopic)",
      "Qalementos (Clement's epistles)",
      "Didascalia (Church order)",
      "Synaxarium (saints' lives)",
      "Ethiopic Book of Jubilees",
      "Mashafa Kidan (Book of the Covenant)",
      "Fetha Nagast (Law of Kings)",
    ],
    writingInfo:
      "Use Geʽez fidäl (ሀ-ፐ) with seven vowel orders per consonant. Gemination marked by doubling or inherent in script. Punctuation via traditional section marks (፡ ። ፣ ፤ ፥ etc.). Numerals in Ge'ez letter-numerals or spelled; never Arabic digits. Maintain manuscript ligatures and abbreviations.",
    fontClass: "font-ethiopic",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Sogdian",
    nativeName: "𐼼𐼴𐼶𐼹𐼷𐼸𐼴",
    sample: "𐼷𐼴𐼺𐼸𐼴",
    translation: "Sogdian (endonym approximation)",
    script: "Sogdian alphabet (Aramaic-derived); Manichaean and Sutra variants",
    color: "from-indigo-500 to-purple-600",
    emoji: "🌌",
    description: "Lingua franca of the Silk Road—Buddhist sutras, Manichaean texts, merchant letters from Dunhuang.",
    topTenWorks: [
      "Ancient Sogdian Letters (c. 313 CE)",
      "Vessantara Jataka (Sogdian trans.)",
      "Diamond Sutra (Sogdian fragments)",
      "Vimalakīrti Sutra (Sogdian)",
      "Sutra of Golden Light (Sogdian)",
      "Manichaean Hymn Cycles",
      "Sogdian Christian Psalms",
      "Xuanzang Biography (Sogdian fragments)",
      "Sogdian Buddhist Dhāraṇī texts",
      "Larger Sukhāvatīvyūha Sutra (Sogdian)",
    ],
    writingInfo:
      "Use Sogdian cursive script (Aramaic heritage), right-to-left. Preserve Aramaic logograms for common words; phonetic spelling otherwise. Sutra script more formal and calligraphic. No modern punctuation—only manuscript dots and section marks. Numerals spelled or via Aramaic word-signs.",
    fontClass: "font-sogdian",
    isRTL: true,
    tier: "core",
  },
  {
    name: "Ugaritic",
    nativeName: "𐎜𐎂𐎗𐎚",
    sample: "𐎁𐎓𐎍",
    translation: "Baal (from the Baal Cycle)",
    script: "Ugaritic cuneiform alphabet (30 letters, c. 1400 BCE)",
    color: "from-orange-700 to-amber-800",
    emoji: "🌄",
    description: "Northwest Semitic language of ancient Ugarit—Baal Cycle, Legend of Keret, and Aqhat Epic.",
    topTenWorks: [
      "Baal Cycle",
      "Legend of Keret (Kirta Epic)",
      "Tale of Aqhat",
      "Rephaim Texts",
      "The Wedding of Nikkal and the Kathirat",
      "The Gracious Gods",
      "Dawn and Dusk (Shachar and Shalim)",
      "Administrative Texts (economic tablets)",
      "Ritual Texts (KTU 1.40, 1.41, etc.)",
      "Ugaritic Incantations",
    ],
    writingInfo:
      "Use Ugaritic cuneiform alphabet (wedge-shaped, 30 signs including three aleph variants). Left-to-right, word-dividers (vertical wedge) standard. No vowels written. Numerals via stroke tallies or spelled; never Arabic digits. Maintain tablet-line formatting.",
    fontClass: "font-cuneiform",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Tocharian A (Ārśi)",
    nativeName: "ārśi-käntwā",
    sample: "yoktsi klyoṣtär",
    translation: "he will seek (sample from Tocharian A texts)",
    script: "Slanting Brahmi (Northern Turkestan variant)",
    color: "from-orange-600 to-red-700",
    emoji: "🐫",
    description: "Easternmost Indo-European language—Buddhist liturgical texts from Turfan oasis (7th–10th c.).",
    topTenWorks: [
      "Maitreyasamiti-Nataka",
      "Ārya-Śūra's Jātakamālā (Tocharian A trans.)",
      "Udānavarga (Tocharian A)",
      "Āgama fragments",
      "Tocharian A Abhidharma texts",
      "Vinaya fragments",
      "Dharmapada verses (Tocharian A)",
      "Avadāna literature",
      "Prajñāpāramitā fragments",
      "Yogalehrbuch",
    ],
    writingInfo:
      "Use slanting Brahmi (northern Turkestan ductus). Left-to-right, maintain ligatures and virāma. Only danda (।) and double-danda (॥) for punctuation. Numerals in Brahmi digits or spelled per witness. Avoid later Devanāgarī conventions; strict adherence to Central Asian Brahmi paleography.",
    fontClass: "font-brahmi",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Tocharian B (Kuśiññe)",
    nativeName: "kuśiññe käntwā",
    sample: "mäkte lāre tuṅk",
    translation: "there was much merit (sample from Tocharian B texts)",
    script: "Slanting Brahmi (Central Asian variant)",
    color: "from-yellow-600 to-orange-700",
    emoji: "🛕",
    description: "Language of Kucha and Turfan—Buddhist sutras, commercial documents, and monastic records (5th–8th c.).",
    topTenWorks: [
      "Udānālaṅkāra",
      "Maitreyasamiti",
      "Pratītyasamutpādagāthā",
      "Vessantara Jātaka (Tocharian B)",
      "Tocharian B Vinaya texts",
      "Wooden tablets (Shorchuk archive)",
      "Metrical Apocalypse of Pseudo-Methodius",
      "Medical and magical texts",
      "Caravan permits and contracts",
      "Kuśiññe Kantwo (pedagogical grammar, 2025)",
    ],
    writingInfo:
      "Use slanting Brahmi as for Tocharian A. Left-to-right, full conjunct ligatures. Punctuation limited to danda marks. Numerals in Brahmi script or spelled. Secular texts may show less formal orthography; liturgical texts maintain strict manuscript conventions.",
    fontClass: "font-brahmi",
    isRTL: false,
    tier: "core",
  },
  {
    name: "Old Turkic (Orkhon)",
    nativeName: "𐰚𐰇𐰚𐱅𐰇𐰼𐰜",
    sample: "𐱅𐰭𐰼𐰃",
    translation: "Tengri (Sky God, from Orkhon inscriptions)",
    script: "Old Turkic runic alphabet (Orkhon script)",
    color: "from-sky-600 to-blue-700",
    emoji: "🐺",
    description: "Language of the Göktürk Khaganate—Orkhon monuments honoring Bilge Khagan and Kül Tigin (8th c.).",
    topTenWorks: [
      "Orkhon inscriptions (Kül Tigin, 732)",
      "Bilge Khagan inscription (735)",
      "Tonyukuk inscription",
      "Yenisei inscriptions",
      "Talas inscriptions",
      "Selenga Stone",
      "Tes inscription",
      "Sudžī inscription",
      "Khüis Tolgoi inscription",
      "Bugut inscription",
    ],
    writingInfo:
      "Use Old Turkic runic alphabet (38 phonetic symbols). Vertical lines for word-dividers. Right-to-left or left-to-right depending on monument orientation (boustrophedon possible). No vowel harmony marked orthographically beyond script. Numerals via tamgas or spelled.",
    fontClass: "font-turkic",
    isRTL: true,
    tier: "partial",
  },
  {
    name: "Etruscan",
    nativeName: "𐌓𐌀𐌔𐌍𐌀",
    sample: "𐌌𐌉𐌍𐌄",
    translation: "Mine (common votive inscription word)",
    script: "Etruscan alphabet (adapted from Euboean Greek)",
    color: "from-purple-700 to-indigo-800",
    emoji: "⚱️",
    description: "Pre-Roman language of Etruria—funerary stelae, Liber Linteus ritual calendar, Pyrgi Tablets.",
    topTenWorks: [
      "Liber Linteus (Zagreb Mummy wrappings)",
      "Pyrgi Tablets (bilingual Etruscan-Phoenician)",
      "Tabula Cortonensis (land contract)",
      "Cippus Perusinus (boundary stone)",
      "Capua Tile (ritual text)",
      "Vicchio Stele (sanctuary dedication)",
      "Tomba dei Rilievi inscriptions",
      "Sarcophagus of Laris Pulenas",
      "Piacenza Liver (divination model)",
      "Magliano Disk",
    ],
    writingInfo:
      "Use Etruscan alphabet (adapted Greek, c. 26 letters). Right-to-left standard. No spaces; word-dividers (dots, interpuncts) occasional. Avoid Greek diacritics; plain letterforms only. Numerals via Etruscan tally system or spelled. Maintain archaic and Neo-Etruscan script distinctions per period.",
    fontClass: "font-etruscan",
    isRTL: true,
    tier: "partial",
  },
  {
    name: "Proto-Norse (Elder Futhark)",
    nativeName: "ᚠᚢᚦᚨᚱᚲ",
    sample: "ᚺᚨᚱᛃᚨ",
    translation: "Harja (personal name, Vimose Comb, c. 160 CE)",
    script: "Elder Futhark (24 runes, c. 150–800 CE)",
    color: "from-stone-500 to-gray-700",
    emoji: "🏞",
    description: "Earliest Germanic runic inscriptions—bracteates, weapons, runestones from Scandinavia and Continental Europe.",
    topTenWorks: [
      "Vimose Comb (c. 160 CE)",
      "Golden Horns of Gallehus (c. 400 CE)",
      "Eggjum Stone (c. 700 CE)",
      "Kylver Stone (c. 400 CE)",
      "Vadstena bracteate",
      "Stentoften Stone",
      "Björketorp Stone",
      "Tune Stone",
      "Einang Stone",
      "Rosseland Stone",
    ],
    writingInfo:
      "Use Elder Futhark (24 runes: ᚠᚢᚦᚨᚱᚲᚷᚹᚺᚾᛁᛃᛇᛈᛉᛊᛏᛒᛖᛗᛚᛜᛟᛞ). No consistent direction—left-to-right, right-to-left, or boustrophedon per witness. No word-dividers or punctuation except occasional marks. Numerals via runes or tallies; no Arabic digits. Bindrunes (ligatures) per inscription.",
    fontClass: "font-runic",
    isRTL: false,
    tier: "partial",
  },
  {
    name: "Runic Old Norse (Younger Futhark)",
    nativeName: "ᚠᚢᚦᚬᚱᚴ",
    sample: "ᚱᚢᚾᚬᚱ",
    translation: "Runes (from Viking Age runestones)",
    script: "Younger Futhark (16 runes, c. 800–1100 CE)",
    color: "from-blue-600 to-sky-700",
    emoji: "⛈️",
    description: "Viking Age runic writing—thousands of runestones, graffiti, inscriptions from Scandinavia, Iceland, Greenland.",
    topTenWorks: [
      "Rök Runestone (longest runic inscription)",
      "Jelling Stones (Harald Bluetooth)",
      "Piraeus Lion (Varangian graffiti)",
      "Kingittorsuaq Runestone (Greenland)",
      "Kensington Runestone (disputed)",
      "Karlevi Runestone (skaldic verse)",
      "Bergen inscriptions (everyday notes)",
      "Bryggen inscriptions (mercantile)",
      "Greenlandic Norse inscriptions",
      "Iceland runic graffiti",
    ],
    writingInfo:
      "Use Younger Futhark (16 runes in long-branch or short-twig variants). Ambiguous vowel representation (e/i → ᛁ; o/u → ᚢ; a → ᚬ/ᛅ). No word-dividers or punctuation. Left-to-right or boustrophedon. Numerals via runes or tally marks; never Arabic digits.",
    fontClass: "font-runic",
    isRTL: false,
    tier: "partial",
  },
  {
    name: "Old Persian (Ariya)",
    nativeName: "𐎠𐎼𐎡𐎹",
    sample: "𐎠𐎢𐎼𐎶𐏀𐎭",
    translation: "Auramazdā (Ahura Mazda, from Behistun Inscription)",
    script: "Old Persian cuneiform (invented for Darius I, c. 525 BCE)",
    color: "from-yellow-700 to-amber-800",
    emoji: "👑",
    description: "Royal language of the Achaemenid Empire—Behistun trilingual, Cyrus Cylinder, monumental inscriptions.",
    topTenWorks: [
      "Behistun Inscription (Darius I)",
      "DNa inscription (Naqsh-e Rostam, Darius I)",
      "XPh inscription (Persepolis, Xerxes I)",
      "DSe inscription (Susa, Darius I)",
      "A²Ha inscription (Hamadan, Artaxerxes II)",
      "DB inscription (Bisotun, Darius I)",
      "DPd inscription (Persepolis Palace)",
      "DZc inscription (Suez Canal stele)",
      "XPl inscription (Persepolis, Xerxes)",
      "A²Sa inscription (Susa, Artaxerxes II)",
    ],
    writingInfo:
      "Use Old Persian cuneiform (semi-alphabetic, 36 phonetic signs + 8 logograms + word-divider). Left-to-right per line, diagonal word-dividers (𐏐). Logograms for common words (king, country, Ahura Mazda). Numerals in Old Persian cuneiform digits or spelled.",
    fontClass: "font-cuneiform",
    isRTL: false,
    tier: "partial",
  },
  {
    name: "Elamite",
    nativeName: "𒁹𒄬𒆷𒁶𒋾",
    sample: "𒄩𒀜𒋾",
    translation: "Haltamti (Elamite endonym for Elam)",
    script: "Elamite cuneiform (adapted from Akkadian)",
    color: "from-stone-700 to-gray-800",
    emoji: "🐍",
    description: "Language of ancient Elam and Achaemenid administration—Persepolis tablets, Behistun trilingual.",
    topTenWorks: [
      "Persepolis Fortification Tablets (c. 509–457 BCE)",
      "Persepolis Treasury Tablets",
      "Behistun Inscription (Elamite version)",
      "Susa Tablets",
      "Chogha Zanbil inscriptions",
      "Treaty of Naram-Sin",
      "Achaemenid Royal Inscriptions (Elamite)",
      "Elamite legal documents",
      "Administrative texts from Susa",
      "Naram-Sin treaty (Old Elamite)",
    ],
    writingInfo:
      "Use Elamite cuneiform (Achaemenid variant or earlier). Left-to-right per line. Syllabic signs, logograms, and determinatives per period. No vowel pointing beyond inherent cuneiform values. Word-dividers optional. Numerals via cuneiform digits or sexagesimal notation.",
    fontClass: "font-cuneiform",
    isRTL: false,
    tier: "partial",
  },
  {
    name: "Classic Maya (Chʼoltiʼ)",
    nativeName: "Chʼoltiʼ",
    sample: "u-tzib-aj",
    translation: "his scribe / the one who writes (common title in inscriptions)",
    script: "Maya hieroglyphs (logosyllabic script)",
    color: "from-green-700 to-lime-700",
    emoji: "🌽",
    description: "Written language of Classic Maya civilization—codices, stelae, painted ceramics (c. 250–900 CE).",
    topTenWorks: [
      "Dresden Codex",
      "Madrid Codex",
      "Paris Codex",
      "Grolier Codex (disputed)",
      "Popol Vuh (transcribed post-conquest, not original glyphs)",
      "Palenque inscriptions (Temple of Inscriptions)",
      "Copán stelae",
      "Quiriguá stelae",
      "Bonampak murals",
      "Yaxchilan lintels",
    ],
    writingInfo:
      "Use Maya glyphs (logograms + syllabic signs) in paired columns, read left-to-right, top-to-bottom per glyph-block pair. No punctuation. Maintain artistic/calligraphic variations per scribe tradition. Numerals via bar-and-dot notation (vigesimal) or head variants. Avoid modern Latin transcription.",
    fontClass: "font-maya",
    isRTL: false,
    tier: "partial",
  },
  {
    name: "Phoenician (Canaanite)",
    nativeName: "𐤊𐤍𐤏𐤍𐤉",
    sample: "𐤀𐤇𐤓𐤌",
    translation: "Ahiram (King Ahiram, from sarcophagus inscription)",
    script: "Phoenician abjad (22 consonants, c. 1050 BCE)",
    color: "from-blue-700 to-indigo-800",
    emoji: "⛵",
    description: "Ancestor of Greek and Aramaic alphabets—merchant inscriptions, royal sarcophagi, Mediterranean trade records.",
    topTenWorks: [
      "Ahiram Sarcophagus (c. 1000 BCE)",
      "Eshmunazar II Sarcophagus",
      "Bodashtart inscriptions",
      "Tabnit Sarcophagus",
      "Kulamuwa Stele",
      "Nora Stone (Sardinia)",
      "Karatepe bilingual (Phoenician-Luwian)",
      "Pyrgi Tablets (Phoenician-Etruscan)",
      "Cippi of Melqart (Malta)",
      "Phoenician seals and stamps",
    ],
    writingInfo:
      "Use Phoenician abjad (22 consonants: 𐤀-𐤕). Right-to-left, no vowels. Word-dividers (vertical stroke) occasional. No punctuation. Numerals via tally marks or spelled; never Arabic digits. Maintain archaic vs. standard Phoenician letterforms per period.",
    fontClass: "font-phoenician",
    isRTL: true,
    tier: "partial",
  },
  {
    name: "Moabite",
    nativeName: "𐤌𐤀𐤁",
    sample: "𐤌𐤔𐤏",
    translation: "Mesha (King Mesha, from Mesha Stele)",
    script: "Moabite variant of Canaanite script",
    color: "from-orange-700 to-red-800",
    emoji: "🐏",
    description: "Northwest Semitic language of Moab—Mesha Stele recounting victories over Israel (9th c. BCE).",
    topTenWorks: [
      "Mesha Stele (Moabite Stone, c. 840 BCE)",
      "El-Kerak inscription fragments",
      "Moabite ostraca",
      "Scattered seal inscriptions",
      "Minor stone fragments",
      "Moabite administrative texts (fragmentary)",
      "Dibon inscriptions",
      "Kerak Plateau inscriptions",
      "Moabite territorial markers",
      "Miscellaneous epigraphic fragments",
    ],
    writingInfo:
      "Use Moabite script (close to Phoenician/Hebrew). Right-to-left, 22-consonant abjad. No vowel pointing. Word-dividers (dots or strokes) occasional. No punctuation. Numerals spelled or via tally marks. Maintain epigraphic conventions per Mesha Stele paleography.",
    fontClass: "font-phoenician",
    isRTL: true,
    tier: "partial",
  },
  {
    name: "Punic (Carthaginian)",
    nativeName: "𐤐𐤍𐤉𐤌",
    sample: "𐤒𐤓𐤕𐤇𐤃𐤔𐤕",
    translation: "Qart-Hadašt (Carthage, 'New City')",
    script: "Punic alphabet (evolved from Phoenician); Neo-Punic cursive",
    color: "from-purple-700 to-indigo-900",
    emoji: "⚓",
    description: "Language of Carthage and its empire—monumental stelae, Cippi of Melqart, and funerary inscriptions.",
    topTenWorks: [
      "Cippi of Melqart (bilingual Punic-Greek)",
      "Carthage funerary stelae (thousands)",
      "Neo-Punic inscriptions (Lepcis Magna)",
      "Punic-Libyan bilingual (Dougga)",
      "Mausoleum at Thugga inscription",
      "Carthage administrative texts",
      "Malta Punic inscriptions",
      "Latino-Punic texts (1st–4th c. CE)",
      "Bir ed-Dreder LP2",
      "Punic seals and coins",
    ],
    writingInfo:
      "Use Punic alphabet (monumental) or Neo-Punic cursive (post-146 BCE). Right-to-left, 22 consonants. Latino-Punic uses Latin letters for Punic language (late period). No vowels except matres lectionis occasionally. Word-dividers rare. Numerals via Phoenician system or spelled.",
    fontClass: "font-phoenician",
    isRTL: true,
    tier: "partial",
  },
];
